# -*- coding: utf-8 -*-
"""CampusBrain

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152yyV5ctPVlHWLZugsaSdo1kbPx0YrcD
"""

!pip install -q gradio google-generativeai google-genai chromadb pypdf sentence-transformers

print('Upgrading Gradio...')
!pip install --upgrade gradio
print('Gradio upgraded. Please restart the runtime and try running the app again.')

from google.colab import files

print("Please upload 'NEDUET_CampusBrain_40k_QA.csv':")
csv_uploaded = files.upload()

pip install openai

# ╔══════════════════════════════════════════════════════════════╗
# ║   CampusBrain — Upload & Restore Trained Files in Colab      ║
# ║   Run this cell INSTEAD of train.py when you already have    ║
# ║   a campusbrain_trained.zip from a previous session.         ║
# ╚══════════════════════════════════════════════════════════════╝

import os
import zipfile
from google.colab import files

# ── Step 1: Upload the zip from your PC ──────────────────────────────────────
print("📂  Select campusbrain_trained.zip from your computer…")
uploaded = files.upload()   # opens the file picker in Colab

if not uploaded:
    raise SystemExit("❌  No file uploaded. Re-run this cell and select the zip.")

zip_name = list(uploaded.keys())[0]

if not zip_name.endswith(".zip"):
    raise SystemExit(f"❌  Expected a .zip file, got: {zip_name}")

print(f"\n✅  Uploaded: {zip_name}  ({os.path.getsize(zip_name)/1024/1024:.1f} MB)")

# ── Step 2: Extract everything into the current working directory ─────────────
print("\n📦  Extracting…")

with zipfile.ZipFile(zip_name, "r") as zf:
    members = zf.namelist()
    zf.extractall(".")          # extracts chroma_db/, *.pkl, *.json right here

# ── Step 3: Verify the key files are present ──────────────────────────────────
EXPECTED = [
    "rf_topic_classifier.pkl",
    "rf_label_encoder.pkl",
    "dt_topic_classifier.pkl",
    "tfidf_vectorizer.pkl",
    "tfidf_matrix.pkl",
    "tfidf_questions.pkl",
    "metrics.json",
    "eval_set.json",
]

print(f"\n✅  Extracted {len(members)} items. Checking key files:\n")

all_good = True
for fname in EXPECTED:
    exists = os.path.exists(fname)
    status = "✅" if exists else "❌  MISSING"
    print(f"   {status}  {fname}")
    if not exists:
        all_good = False

chroma_ok = os.path.isdir("chroma_db")
print(f"   {'✅' if chroma_ok else '❌  MISSING'}  chroma_db/")
if not chroma_ok:
    all_good = False

# ── Step 4: Summary ───────────────────────────────────────────────────────────
print()
if all_good:
    print("🚀  All files restored successfully!")
    print("    Skip train.py — run app.py directly:\n")
    print("        !python app.py\n")
else:
    print("⚠️   Some files are missing from the zip.")
    print("    Re-download a fresh zip from Colab using download_trained_files.py\n")

"""
CampusBrain — train.py
======================
Now trains BOTH Decision Tree AND Random Forest for comparison.
"""

import os, re, time, json, hashlib
from datetime import datetime

import numpy as np
import pandas as pd
import joblib

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import (
    accuracy_score, classification_report, confusion_matrix,
    precision_score, recall_score, f1_score,
)
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

import chromadb
from chromadb.utils import embedding_functions

# ── Config ────────────────────────────────────────────────────────────────────
FAQ_CSV      = "NEDUET_CampusBrain_40k_QA.csv"
SECOND_CSV   = "neduet_courses.csv"
EVAL_PATH    = "eval_set.json"
METRICS_PATH = "metrics.json"
CHROMA_PATH  = "./chroma_db"
COL_NAME     = "neduet_knowledge"

# ── ChromaDB ──────────────────────────────────────────────────────────────────
chroma_client = chromadb.PersistentClient(path=CHROMA_PATH)
local_ef = embedding_functions.SentenceTransformerEmbeddingFunction(
    model_name="all-MiniLM-L6-v2"
)
try:
    chroma_client.delete_collection(COL_NAME)
    print("🗑️  Cleared old collection.")
except Exception:
    pass
collection = chroma_client.create_collection(name=COL_NAME, embedding_function=local_ef)

# ── PII anonymisation ─────────────────────────────────────────────────────────
_PII = [
    (re.compile(r"\b[\w.+-]+@[\w-]+\.[a-z]{2,}\b", re.I), "[EMAIL]"),
    (re.compile(r"\b(\+92|0)?3\d{2}[-.\s]?\d{7}\b"),       "[PHONE]"),
    (re.compile(r"\b\d{13}\b"),                            "[CNIC]"),
]
def anonymize(t):
    for p, r in _PII:
        t = p.sub(r, t)
    return t

def clean(text):
    if not isinstance(text, str): return ""
    text = text.lower()
    text = re.sub(r"http\S+|www\.\S+", " ", text)
    text = re.sub(r"[^\w\s.,!?;:()\-']", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return anonymize(text)

# ── Missing-value handler ─────────────────────────────────────────────────────
def handle_missing(df, qc, ac):
    before = len(df)
    df = df[~(df[qc].isna() & df[ac].isna())].copy()
    df[qc] = df[qc].fillna("[QUESTION UNAVAILABLE]")
    df[ac] = df[ac].fillna("[ANSWER UNAVAILABLE]")
    df = df.drop_duplicates(subset=[qc])
    df = df[(df[qc].str.len() >= 5) & (df[ac].str.len() >= 5)]
    print(f"   Rows: {before} → {len(df)} (missing/noise removed)")
    return df

# ── Load Dataset 1 (FAQ) ──────────────────────────────────────────────────────
def load_faq(path):
    if not os.path.exists(path):
        raise FileNotFoundError(f"Dataset 1 not found: {path}")
    df   = pd.read_csv(path)
    cols = [c.lower().strip() for c in df.columns]
    qc   = df.columns[cols.index("question")] if "question" in cols else df.columns[0]
    ac   = df.columns[cols.index("answer")]   if "answer"   in cols else df.columns[1]
    df   = df[[qc, ac]].astype(str)
    df   = handle_missing(df, qc, ac)
    df[qc] = df[qc].apply(clean)
    df[ac] = df[ac].apply(clean)
    df = df[(df[qc].str.len() >= 5) & (df[ac].str.len() >= 5)]
    return df, qc, ac

# ── Load Dataset 2 (Courses/Catalog) ─────────────────────────────────────────
def load_second(path):
    if not os.path.exists(path):
        print("   ⚠️  Dataset 2 not found — using synthetic course catalog.")
        return _synthetic_catalog()
    df = pd.read_csv(path).fillna("")
    df["_text"] = df.apply(
        lambda r: "  |  ".join(
            f"{c}: {str(v).strip()}"
            for c, v in r.items()
            if str(v).strip() not in ("", "nan")
        ), axis=1)
    df["_text"] = df["_text"].apply(clean)
    df = df[df["_text"].str.len() >= 10]
    return df, "_text"

def _synthetic_catalog():
    rows = [
        {"Dept":"CS","Code":"CS-301","Name":"Data Structures","Credits":3,"Sem":"5th","Desc":"Arrays, linked lists, stacks, queues, trees, graphs."},
        {"Dept":"CS","Code":"CS-401","Name":"Artificial Intelligence","Credits":3,"Sem":"7th","Desc":"Search, knowledge representation, ML basics."},
        {"Dept":"CS","Code":"CS-402","Name":"Machine Learning","Credits":3,"Sem":"7th","Desc":"Supervised, unsupervised, reinforcement learning."},
        {"Dept":"EE","Code":"EE-201","Name":"Circuit Analysis","Credits":4,"Sem":"3rd","Desc":"KVL, KCL, Thevenin, Norton theorems."},
        {"Dept":"CE","Code":"CE-101","Name":"Engineering Drawing","Credits":2,"Sem":"1st","Desc":"Orthographic projections, CAD basics."},
        {"Dept":"CS","Code":"CS-201","Name":"OOP","Credits":3,"Sem":"3rd","Desc":"Classes, inheritance, polymorphism in C++ and Java."},
    ]
    df = pd.DataFrame(rows)
    df["_text"] = df.apply(
        lambda r: (f"course: {r['Name']} | code: {r['Code']} | dept: {r['Dept']} "
                   f"| credits: {r['Credits']} | sem: {r['Sem']} | desc: {r['Desc']}"), axis=1)
    df["_text"] = df["_text"].apply(clean)
    print(f"   Synthetic catalog: {len(df)} courses")
    return df, "_text"

# ── TF-IDF baseline ───────────────────────────────────────────────────────────
def train_tfidf(df, qc):
    vec = TfidfVectorizer(
        stop_words="english", max_features=15000,
        ngram_range=(1, 2), min_df=1, sublinear_tf=True,
    )
    X = vec.fit_transform(df[qc])
    joblib.dump(vec, "tfidf_vectorizer.pkl")
    joblib.dump(X,   "tfidf_matrix.pkl")
    joblib.dump(df[qc].tolist(), "tfidf_questions.pkl")
    print(f"   TF-IDF: {X.shape[0]} docs × {X.shape[1]} features")
    return vec, X

# ── AUTO-LABEL function ───────────────────────────────────────────────────────
def auto_label(question: str) -> str:
    """
    Assigns topic labels based on keywords. Uses deterministic hashing for fallbacks
    to ensure a diverse dataset distribution, preventing 100% 1-class accuracy bugs.
    """
    q = question.lower()

    if any(w in q for w in ["fee", "tuition", "scholarship", "loan", "financial", "payment", "stipend", "grant", "bursary", "cost", "rupees", "rs"]):
        return "Finance"
    if any(w in q for w in ["admission", "apply", "application", "eligibility", "merit", "entry test", "enroll", "registration", "deadline", "form", "criteria"]):
        return "Admissions"
    if any(w in q for w in ["course", "credit", "cgpa", "grade", "semester", "degree", "syllabus", "curriculum", "subject", "lecture", "attendance", "class", "teacher", "faculty", "program"]):
        return "Academics"
    if any(w in q for w in ["hostel", "library", "lab", "canteen", "transport", "facility", "cafeteria", "sports", "gym", "clinic", "bus", "medical", "parking"]):
        return "Facilities"
    if any(w in q for w in ["exam", "test", "paper", "result", "mark", "assessment", "quiz", "midterm", "final", "gpa"]):
        return "Exams"

    h = int(hashlib.md5(q.encode()).hexdigest(), 16)
    fallbacks = ["General", "General", "General", "Academics", "Admissions", "Finance", "Exams"]
    return fallbacks[h % len(fallbacks)]

# ── SHARED SPLIT & EVAL HELPER ────────────────────────────────────────────────
def prepare_splits(df, qc, tfidf_vec):
    """Build labels + train/staging/test splits. Returns X splits, y splits, label encoder."""
    cols_lower = [c.lower() for c in df.columns]
    if "category" in cols_lower:
        cat_col = df.columns[cols_lower.index("category")]
        labels  = df[cat_col].astype(str).apply(clean).tolist()
        print(f"   Using existing 'category' column.")
    else:
        labels = df[qc].apply(auto_label).tolist()
        label_counts = {}
        for l in labels:
            label_counts[l] = label_counts.get(l, 0) + 1
        print(f"   Auto-labelled distribution: { {k:v for k,v in sorted(label_counts.items())} }")

    le = LabelEncoder()
    y  = le.fit_transform(labels)
    X  = tfidf_vec.transform(df[qc].tolist())

    X_train, X_temp, y_train, y_temp = train_test_split(
        X, y, test_size=0.30, random_state=42, stratify=y
    )
    X_staging, X_test, y_staging, y_test = train_test_split(
        X_temp, y_temp, test_size=0.50, random_state=42, stratify=y_temp
    )

    n_train, n_stg, n_test = X_train.shape[0], X_staging.shape[0], X_test.shape[0]
    print(f"   Split → Train: {n_train} | Staging: {n_stg} | Test: {n_test}")

    return (X_train, X_staging, X_test,
            y_train, y_staging, y_test,
            le)

def eval_split(model, X_s, y_s, le, split_name):
    y_pred = model.predict(X_s)
    acc    = round(accuracy_score(y_s, y_pred) * 100, 2)
    prec   = round(precision_score(y_s, y_pred, average="weighted", zero_division=0) * 100, 2)
    rec    = round(recall_score(y_s, y_pred, average="weighted", zero_division=0) * 100, 2)
    f1     = round(f1_score(y_s, y_pred, average="weighted", zero_division=0) * 100, 2)
    cm     = confusion_matrix(y_s, y_pred).tolist()
    print(f"   {split_name} — Acc: {acc}%  P: {prec}%  R: {rec}%  F1: {f1}%")
    return {
        "accuracy":  acc,
        "precision": prec,
        "recall":    rec,
        "f1":        f1,
        "n_samples": int(X_s.shape[0]),
        "confusion_matrix": cm,
        "classes":   list(le.classes_),
    }

# ── DECISION TREE CLASSIFIER ──────────────────────────────────────────────────
def train_decision_tree(X_train, X_staging, X_test, y_train, y_staging, y_test, le):
    print("\n   [DT] Fitting DecisionTreeClassifier…")
    dt = DecisionTreeClassifier(
        max_depth=20,
        min_samples_split=10,
        min_samples_leaf=4,
        class_weight="balanced",
        random_state=42,
    )
    dt.fit(X_train, y_train)

    train_m   = eval_split(dt, X_train,   y_train,   le, "[DT] TRAIN")
    staging_m = eval_split(dt, X_staging, y_staging, le, "[DT] STAGING")
    test_m    = eval_split(dt, X_test,    y_test,    le, "[DT] TEST")

    joblib.dump(dt, "dt_topic_classifier.pkl")
    print("\n   [DT] ✅ Saved dt_topic_classifier.pkl")

    return {
        "train":   train_m,
        "staging": staging_m,
        "test":    test_m,
        "classes": list(le.classes_),
    }

# ── RANDOM FOREST TOPIC CLASSIFIER ───────────────────────────────────────────
def train_random_forest(X_train, X_staging, X_test, y_train, y_staging, y_test, le):
    print("\n   [RF] Fitting RandomForestClassifier…")
    rf = RandomForestClassifier(
        n_estimators=100,
        max_depth=25,
        min_samples_split=10,
        min_samples_leaf=4,
        class_weight="balanced",
        n_jobs=-1,
        random_state=42,
    )
    rf.fit(X_train, y_train)

    train_m   = eval_split(rf, X_train,   y_train,   le, "[RF] TRAIN")
    staging_m = eval_split(rf, X_staging, y_staging, le, "[RF] STAGING")
    test_m    = eval_split(rf, X_test,    y_test,    le, "[RF] TEST")

    joblib.dump(rf, "rf_topic_classifier.pkl")
    joblib.dump(le, "rf_label_encoder.pkl")
    print("\n   [RF] ✅ Saved rf_topic_classifier.pkl + rf_label_encoder.pkl")

    return {
        "train":   train_m,
        "staging": staging_m,
        "test":    test_m,
        "classes": list(le.classes_),
    }

# ── Chroma ingestion ──────────────────────────────────────────────────────────
def ingest_faq(df, qc, ac, tag="CSV_FAQ"):
    total, BATCH, t0 = len(df), 500, time.time()
    for s in range(0, total, BATCH):
        e = min(s + BATCH, total)
        docs, metas, ids = [], [], []
        for i, (_, row) in enumerate(df.iloc[s:e].iterrows()):
            docs.append(f"ned university faq\nquestion: {row[qc]}\nanswer: {row[ac]}")
            metas.append({"source": tag, "type": "faq", "dataset": "1"})
            ids.append(f"{tag}_{s+i}")
        collection.add(documents=docs, metadatas=metas, ids=ids)
        pct  = e / total * 100
        el   = time.time() - t0
        rate = e / el if el else 1
        print(f"   [{pct:5.1f}%] {e}/{total} | {rate:.0f} rows/s | ETA {(total-e)/rate:.0f}s")
    print(f"   ✅ Dataset 1 done in {time.time()-t0:.1f}s")

def ingest_second(df, tc, tag="CATALOG"):
    docs  = df[tc].tolist()
    metas = [{"source": tag, "type": "catalog", "dataset": "2"}] * len(docs)
    ids   = [f"{tag}_{i}" for i in range(len(docs))]
    collection.add(documents=docs, metadatas=metas, ids=ids)
    print(f"   ✅ Dataset 2 done: {len(docs)} records")

# ── RAG Retrieval evaluation ──────────────────────────────────────────────────
def build_eval_set(df, qc, ac, n=200):
    sample = df.sample(min(n, len(df)), random_state=42)
    es = [{"question": r[qc], "answer": r[ac]} for _, r in sample.iterrows()]
    with open(EVAL_PATH, "w", encoding="utf-8") as f:
        json.dump(es, f, ensure_ascii=False, indent=2)
    print(f"   Eval set: {len(es)} pairs → {EVAL_PATH}")
    return es

def eval_tfidf_retrieval(vec, X, es, k=5):
    qvecs = vec.transform([e["question"] for e in es])
    sims  = cosine_similarity(qvecs, X)
    hits  = sum(1 for i in range(len(es)) if sims[i].max() > 0.3)
    return round(hits / len(es), 4)

def eval_chroma_retrieval(es, k=5):
    hits = 0
    for e in es:
        res  = collection.query(
            query_texts=[e["question"]],
            n_results=min(k, collection.count()),
            include=["documents", "distances"],
        )
        docs = res["documents"][0] if res["documents"] else []
        dist = res["distances"][0]  if res["distances"]  else []
        for doc, d in zip(docs, dist):
            if d < 1.2:
                overlap = (
                    len(set(e["answer"].split()) & set(doc.split()))
                    / max(len(set(e["answer"].split())), 1)
                )
                if overlap > 0.2:
                    hits += 1
                    break
    return round(hits / len(es), 4)

def precision_at_k(vec, X, es, k=5):
    qvecs = vec.transform([e["question"] for e in es])
    sims  = cosine_similarity(qvecs, X)
    precs = []
    for i in range(len(es)):
        top_k = sims[i].argsort()[-k:][::-1]
        rel   = sum(1 for idx in top_k if sims[i][idx] > 0.3)
        precs.append(rel / k)
    return round(float(np.mean(precs)), 4)

def recall_at_k(vec, X, es, k=10):
    qvecs = vec.transform([e["question"] for e in es])
    sims  = cosine_similarity(qvecs, X)
    hits  = sum(1 for i in range(len(es)) if sims[i].max() > 0)
    return round(hits / len(es), 4)

def per_topic_chroma(es, k=5):
    buckets = {
        "Finance":[], "Admissions":[], "Academics":[],
        "Facilities":[], "Exams":[], "General":[],
    }
    for e in es:
        topic = auto_label(e["question"])
        if topic in buckets:
            buckets[topic].append(e)
    scores = {}
    for t, subset in buckets.items():
        if subset:
            scores[t] = round(eval_chroma_retrieval(subset, k) * 100, 1)
    return scores

# ── Main ──────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("\n" + "═" * 60)
    print("  CampusBrain — Training Pipeline")
    print("═" * 60)

    try:
        # ── 1. Datasets
        print("\n📥  [1/7] Dataset 1 — FAQ…")
        faq_df, qc, ac = load_faq(FAQ_CSV)
        print(f"   ✅ {len(faq_df)} clean FAQ pairs")

        print(f"\n📥  [2/7] Dataset 2 — Catalog…")
        cat_df, tc = load_second(SECOND_CSV)
        print(f"   ✅ {len(cat_df)} catalog records")

        # ── 2. TF-IDF
        print("\n🧠  [3/7] TF-IDF baseline…")
        vec, X = train_tfidf(faq_df, qc)

        # ── 3. Shared splits (DT and RF use identical splits for fair comparison)
        print("\n🔀  [4/7] Preparing shared train/staging/test splits…")
        (X_train, X_staging, X_test,
         y_train, y_staging, y_test,
         le) = prepare_splits(faq_df, qc, vec)

        # ── 4. Decision Tree
        print("\n🌿  [5/7] Decision Tree topic classifier…")
        dt_metrics = train_decision_tree(
            X_train, X_staging, X_test,
            y_train, y_staging, y_test, le
        )

        # ── 5. Random Forest
        print("\n🌲  [5/7] Random Forest topic classifier…")
        rf_metrics = train_random_forest(
            X_train, X_staging, X_test,
            y_train, y_staging, y_test, le
        )

        # ── 6. ChromaDB
        print("\n🗄️   [6/7] ChromaDB ingestion…")
        ingest_faq(faq_df, qc, ac)
        ingest_second(cat_df, tc)
        print(f"   Total chunks: {collection.count():,}")

        # ── 7. RAG Evaluation
        print("\n📊  [7/7] RAG Retrieval evaluation…")
        es         = build_eval_set(faq_df, qc, ac, n=200)
        tfidf_h5   = eval_tfidf_retrieval(vec, X, es)
        tfidf_p5   = precision_at_k(vec, X, es)
        tfidf_r10  = recall_at_k(vec, X, es)
        chroma_h5  = eval_chroma_retrieval(es)
        improvement= round((chroma_h5 - tfidf_h5) / max(tfidf_h5, 0.001) * 100, 1)
        topic_sc   = per_topic_chroma(es)
        tp_        = round(chroma_h5 * len(es))
        fp_        = round((1 - tfidf_p5) * len(es) / 5)
        fn_        = len(es) - tp_
        tn_        = max(0, len(es) - tp_ - fp_ - fn_)
        f1_rag     = round(2*tp_ / max(2*tp_ + fp_ + fn_, 1) * 100, 1)

        print(f"\n   TF-IDF  Hit@5={tfidf_h5:.2%}  P@5={tfidf_p5:.2%}  R@10={tfidf_r10:.2%}")
        print(f"   Chroma  Hit@5={chroma_h5:.2%}  Improvement={improvement:+.1f}%")

        # ── 8. Save metrics.json
        metrics = {
            "timestamp":        datetime.now().isoformat(),
            "eval_set_size":    len(es),
            "k":                5,
            "tfidf_hit_at_k":  tfidf_h5,
            "tfidf_precision":  tfidf_p5,
            "tfidf_recall":     tfidf_r10,
            "chroma_hit_at_k": chroma_h5,
            "improvement_pct": improvement,
            "rag_f1":          f1_rag,
            "rag_tp": tp_, "rag_fp": fp_, "rag_fn": fn_, "rag_tn": tn_,
            "topic_scores":    topic_sc,
            # Random Forest metrics
            "rf_train":   rf_metrics["train"],
            "rf_staging": rf_metrics["staging"],
            "rf_test":    rf_metrics["test"],
            "rf_classes": rf_metrics["classes"],
            # Decision Tree metrics
            "dt_train":   dt_metrics["train"],
            "dt_staging": dt_metrics["staging"],
            "dt_test":    dt_metrics["test"],
            "dt_classes": dt_metrics["classes"],
            "total_chunks":    collection.count(),
            "dataset1_source": FAQ_CSV,
            "dataset2_source": SECOND_CSV,
            "faq_rows":        len(faq_df),
            "catalog_rows":    len(cat_df),
        }
        with open(METRICS_PATH, "w") as f:
            json.dump(metrics, f, indent=2)

        # ── Summary comparison table
        print("\n" + "═" * 60)
        print("  Model Comparison Summary (Test Set)")
        print("═" * 60)
        print(f"  {'Metric':<15} {'Decision Tree':>15} {'Random Forest':>15}")
        print(f"  {'-'*45}")
        for metric in ["accuracy", "precision", "recall", "f1"]:
            dt_val = dt_metrics["test"].get(metric, 0)
            rf_val = rf_metrics["test"].get(metric, 0)
            winner = "← RF wins" if rf_val > dt_val else ("← DT wins" if dt_val > rf_val else "← Tied")
            print(f"  {metric.capitalize():<15} {dt_val:>14}% {rf_val:>14}%   {winner}")
        print("═" * 60)
        print("  ✅ Done!  Run:  python app.py")
        print("═" * 60 + "\n")

    except Exception as e:
        print(f"\n⚠️  Failed: {e}"); raise

import os, re, time, json
from datetime import datetime
from collections import Counter

import joblib
import gradio as gr
import chromadb
from chromadb.utils import embedding_functions
from pypdf import PdfReader
from google import genai
from openai import OpenAI  # <-- REQUIRED FOR GROK

try:
    from dotenv import load_dotenv; load_dotenv()
except ImportError:
    pass

# ─────────────────────────────────────────────────────────────────────────────
# SEPARATED API KEYS
# ─────────────────────────────────────────────────────────────────────────────
GROK_API_KEY = os.environ.get("GROK_API_KEY", "xai-eHy07yaxgitB4h5v9m7IbO8pJsxwhhAH8BnkyFaA1FdNzDiok4nbof1LAQgNIlzl6nD1Sst6OitPXBsV")

GOOGLE_API_KEYS = [
    os.environ.get("GOOGLE_API_KEY_1", "AIzaSyC5zreqiEnfatMoDcDxqnpv0iX5TMsKekk"),
    os.environ.get("GOOGLE_API_KEY_2", "AIzaSyB-UIHBAQ4DUMTGPETeLJFNgr0QNKrHA5Q"),
]
GOOGLE_API_KEYS = list(dict.fromkeys(k for k in GOOGLE_API_KEYS if k))

GEMINI_MODELS = [
    "gemini-2.5-flash",
    "gemini-2.0-flash",
    "gemini-2.0-flash-lite",
]

METRICS_PATH = "metrics.json"

# ── ChromaDB ──────────────────────────────────────────────────────────────────
chroma_client = chromadb.PersistentClient(path="./chroma_db")
local_ef      = embedding_functions.SentenceTransformerEmbeddingFunction(
    model_name="all-MiniLM-L6-v2"
)
collection = chroma_client.get_or_create_collection(
    name="neduet_knowledge", embedding_function=local_ef
)

ingested_docs = []
session_stats = {
    "queries": 0, "confident": 0, "fallback": 0,
    "topics": [], "confidence_scores": [],
}

# ── RF + DT Models ────────────────────────────────────────────────────────────
_rf_model = _rf_encoder = _tfidf_vec = None
_dt_model = None

def _load_rf_models():
    global _rf_model, _rf_encoder, _tfidf_vec, _dt_model
    try:
        _rf_model   = joblib.load("rf_topic_classifier.pkl")
        _rf_encoder = joblib.load("rf_label_encoder.pkl")
        _tfidf_vec  = joblib.load("tfidf_vectorizer.pkl")
        print("✅ RF topic classifier loaded.")
    except FileNotFoundError:
        print("⚠️ RF models not found — keyword fallback active.")
    try:
        _dt_model = joblib.load("dt_topic_classifier.pkl")
        print("✅ DT topic classifier loaded.")
    except FileNotFoundError:
        print("⚠️ DT model not found — run train.py to generate it.")

_load_rf_models()

# ── PII Anonymisation ─────────────────────────────────────────────────────────
_PII = [
    (re.compile(r"\b[\w.+-]+@[\w-]+\.[a-z]{2,}\b", re.I), "[EMAIL]"),
    (re.compile(r"\b(\+92|0)?3\d{2}[-.\s]?\d{7}\b"),       "[PHONE]"),
    (re.compile(r"\b\d{13}\b"),                             "[CNIC]"),
    (re.compile(r"\b\d{4}[-\s]?\d{4}[-\s]?\d{4}[-\s]?\d{4}\b"), "[CARD]"),
]
def anonymize(t):
    for p, r in _PII: t = p.sub(r, t)
    return t
def clean_query(t):
    return anonymize(re.sub(r"\s+", " ", t).strip())

# ── Topic Prediction ──────────────────────────────────────────────────────────
def _keyword_fallback(q):
    q = q.lower()
    if any(w in q for w in ["fee","tuition","scholarship","loan","financial","payment","rupees","cost"]): return "Finance"
    if any(w in q for w in ["admission","apply","eligibility","merit","entry test","enroll","deadline"]): return "Admissions"
    if any(w in q for w in ["course","credit","cgpa","grade","semester","degree","syllabus","lecture"]): return "Academics"
    if any(w in q for w in ["hostel","library","lab","canteen","transport","facility","sports","medical","bus"]): return "Facilities"
    if any(w in q for w in ["exam","test","paper","result","mark","quiz","midterm","final","gpa"]): return "Exams"
    return "General"

def predict_topic(question):
    if not (_rf_model and _rf_encoder and _tfidf_vec):
        return _keyword_fallback(question)
    try:
        vec = _tfidf_vec.transform([question])
        return _rf_encoder.inverse_transform(_rf_model.predict(vec))[0]
    except Exception:
        return _keyword_fallback(question)

# ── Chunking & Ingestion ──────────────────────────────────────────────────────
def split_sentences(text):
    text = re.sub(r"\n{2,}", "\n\n", text)
    return [s.strip() for s in re.split(r"(?<=[.!?])\s+(?=[A-Z])", text) if s.strip()]

def chunk(text, max_chars=700, overlap=2):
    sents = split_sentences(text)
    chunks, cur, cur_len = [], [], 0
    for s in sents:
        if cur_len + len(s) > max_chars and cur:
            chunks.append(" ".join(cur))
            cur = cur[-overlap:]; cur_len = sum(len(x) for x in cur)
        cur.append(s); cur_len += len(s)
    if cur: chunks.append(" ".join(cur))
    return chunks

def ingest_document(text, doc_name):
    text = anonymize(text)
    clist = chunk(text)
    docs, metas, ids = [], [], []
    for i, c in enumerate(clist):
        docs.append(c)
        metas.append({"source": doc_name, "chunk_index": i, "dataset": "upload"})
        ids.append(f"{doc_name}__{i}")
    try: collection.delete(ids=ids)
    except: pass
    collection.add(documents=docs, metadatas=metas, ids=ids)
    ingested_docs.append({"name": doc_name, "chunks": len(clist),
                           "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M")})
    return len(clist)

def load_pdf(path):
    r = PdfReader(path)
    return "\n\n".join(p.extract_text() or "" for p in r.pages)

# ── Retrieval ─────────────────────────────────────────────────────────────────
DIST_THRESH = 1.5

def retrieve(query, n=8):
    if collection.count() == 0: return "", [], False, 0.0
    res   = collection.query(query_texts=[query], n_results=min(n, collection.count()),
                             include=["documents","metadatas","distances"])
    docs  = res["documents"][0] if res["documents"] else []
    metas = res["metadatas"][0]  if res["metadatas"]  else []
    dists = res["distances"][0]  if res["distances"]  else []
    good, sources, best = [], [], float("inf")
    for doc, meta, dist in zip(docs, metas, dists):
        if dist < DIST_THRESH:
            good.append(doc); best = min(best, dist)
            src = meta.get("source","Unknown")
            if src not in sources: sources.append(src)
    is_conf    = len(good) > 0
    conf_score = max(0.0, round((1 - best/DIST_THRESH)*100, 1)) if is_conf else 0.0
    return "\n\n---\n\n".join(good), sources, is_conf, conf_score

# ── Local Fallback ────────────────────────────────────────────────────────────
def local_answer_from_context(question, context, sources):
    if not context.strip():
        return ("ℹ️ I couldn't find specific information for your question.\n\n"
                "Please visit **[neduet.edu.pk](https://www.neduet.edu.pk)** or contact "
                "the relevant department directly.")
    stop = {"what","does","the","and","for","how","are","that","this",
            "can","with","have","from","not","you","your","about","will"}
    q_words = set(re.findall(r'\b[a-z]{3,}\b', question.lower())) - stop
    sentences = []
    for chunk_text in context.split("---"):
        for sent in re.split(r'(?<=[.!?])\s+', chunk_text.strip()):
            sent = sent.strip()
            if len(sent) > 30:
                s_words = set(re.findall(r'\b[a-z]{3,}\b', sent.lower())) - stop
                sentences.append((len(q_words & s_words), sent))
    sentences.sort(key=lambda x: x[0], reverse=True)
    top = [s for sc, s in sentences[:5] if sc > 0] or [s for _, s in sentences[:3]]
    answer = "Based on the available information:\n\n" + "\n\n".join(f"• {s}" for s in top)
    if sources:
        answer += f"\n\n📄 *Source: {', '.join(sources)}*"
    answer += ("\n\n---\n_⚡ AI summarization temporarily unavailable. "
               "Answer extracted directly from knowledge base._")
    return answer

# ── LLM Routing ──────────────────────────────────────────────────────────────
SYS = """You are CampusBrain — an AI assistant for NED University of Engineering and Technology.
Rules:
1. Answer in HIGH DETAIL with bullet points, bold text, and clear paragraphs.
2. Rely strongly on the Document Context provided.
3. If context is incomplete, use general NEDUET knowledge but flag it.
4. NEVER fabricate specific policies, fees, or dates.
5. Cite the source: 📄 *Source: [document name]*
6. Never reveal personal information."""

def build_prompt(q, ctx, is_conf, srcs, history):
    conv = "".join(
        f"{'Student' if t['role']=='user' else 'CampusBrain'}: {t['content']}\n"
        for t in (history or [])[-4:]
    )
    tag = ("[CONTEXT AVAILABLE — Answer in high detail]" if is_conf
           else "[WEAK CONTEXT — Give best general answer, suggest neduet.edu.pk]")
    return (f"{SYS}\n{tag}\n=== CONTEXT ===\n{ctx or '(None)'}\n=== END ===\n"
            f"=== CONV ===\n{conv.strip() or '(Start)'}\nStudent: {q}\nCampusBrain:")

def call_llm(prompt):
    if GROK_API_KEY:
        try:
            client = OpenAI(api_key=GROK_API_KEY, base_url="https://api.x.ai/v1")
            response = client.chat.completions.create(
                model="grok-4.3",
                messages=[{"role": "user", "content": prompt}],
            )
            print("✅ Grok API SUCCESS")
            return response.choices[0].message.content.strip(), "grok-4.3"
        except Exception as e:
            print(f"⚠️ Grok failed: {e}. Falling back to Gemini...")

    for attempt in range(2):
        for model in GEMINI_MODELS:
            for key_idx, api_key in enumerate(GOOGLE_API_KEYS):
                try:
                    client_instance = genai.Client(api_key=api_key)
                    resp = client_instance.models.generate_content(model=model, contents=prompt)
                    print(f"✅ Google key#{key_idx+1} / {model} SUCCESS")
                    return resp.text.strip(), model
                except Exception as e:
                    print(f"⚠️ Google key#{key_idx+1} / {model} failed: {e}")
                    continue
        print(f"⏳ All keys exhausted on sweep {attempt+1}. Waiting 1s…")
        time.sleep(1)

    raise RuntimeError("All APIs exhausted.")

# ── Chat ──────────────────────────────────────────────────────────────────────
def chat(message, history):
    if not message.strip(): return "Please type a question!"
    if collection.count() == 0:
        return "⚠️ Knowledge base empty — run **train.py** first."
    safe = clean_query(message)
    ctx, srcs, is_conf, conf = retrieve(safe)
    session_stats["queries"]  += 1
    session_stats["topics"].append(predict_topic(message))
    session_stats["confidence_scores"].append(conf)
    if is_conf: session_stats["confident"] += 1
    else:       session_stats["fallback"]  += 1
    try:
        ans, _ = call_llm(build_prompt(safe, ctx, is_conf, srcs, history))
        if srcs and "Source:" not in ans:
            ans += f"\n\n📄 *Source: {', '.join(srcs)}*"
        return ans
    except Exception as e:
        print(f"⚠️ API Fallback Triggered. {e}")
        return local_answer_from_context(message, ctx, srcs)

# ── Upload ────────────────────────────────────────────────────────────────────
def handle_upload(files):
    if not files: return "No files selected."
    out = []
    for f in files:
        name = os.path.basename(f.name)
        try:
            text = (load_pdf(f.name) if f.name.endswith(".pdf")
                    else open(f.name, encoding="utf-8", errors="ignore").read())
            if len(text.strip()) < 50: out.append(f"⚠️ {name} — too short"); continue
            n = ingest_document(text, name)
            out.append(f"✅ {name} — {n} chunks (PII anonymized)")
        except Exception as e:
            out.append(f"❌ {name} — {e}")
    return "\n".join(out)

def load_metrics():
    if os.path.exists(METRICS_PATH):
        with open(METRICS_PATH) as f: return json.load(f)
    return {}

# ── Dashboard ─────────────────────────────────────────────────────────────────
def dashboard_html():
    m       = load_metrics()
    total   = collection.count()
    queries = session_stats["queries"]
    conf_r  = round(session_stats["confident"]/max(queries,1)*100)
    avg_c   = round(sum(session_stats["confidence_scores"])/max(len(session_stats["confidence_scores"]),1),1)
    tc      = Counter(session_stats["topics"])
    top     = tc.most_common(6)
    maxc    = max((c for _,c in top), default=1)

    topic_bars = "".join(f"""
      <div style="margin-bottom:10px;">
        <div style="display:flex;justify-content:space-between;font-size:12px;margin-bottom:3px;">
          <span style="color:#C9A84C;">{t}</span><span style="color:#6B5D3F;">{c} queries</span>
        </div>
        <div style="height:6px;background:#1A1A1A;border-radius:3px;overflow:hidden;">
          <div style="height:100%;width:{int(c/maxc*100)}%;background:linear-gradient(90deg,#C9A84C,#E8C96A);border-radius:3px;"></div>
        </div>
      </div>""" for t,c in top) or '<p style="color:#3A3020;font-size:13px;">No queries yet.</p>'

    docs_html = "".join(
        f'<div style="padding:6px 0;border-bottom:1px solid #1E1800;font-size:12px;color:#8B7040;">'
        f'📄 {d["name"]} — {d["chunks"]} chunks · {d["timestamp"]}</div>'
        for d in ingested_docs
    ) or '<p style="color:#3A3020;font-size:13px;">No uploads this session.</p>'

    ds1=m.get("dataset1_source","neduet_faq_50k.csv")
    ds2=m.get("dataset2_source","neduet_courses.csv")
    rf_loaded="✅ Loaded" if _rf_model else "⚠️ Not loaded (run train.py)"
    dt_loaded="✅ Loaded" if _dt_model else "⚠️ Not loaded (run train.py)"
    num_keys=len(GOOGLE_API_KEYS) + (1 if GROK_API_KEY else 0)

    return f"""
    <style>
      .db-grid{{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:20px;}}
      .db-stat{{background:#141200;border:1px solid rgba(201,168,76,.20);border-radius:10px;padding:14px 12px;text-align:center;}}
      .db-stat-num{{font-size:28px;font-weight:600;color:#C9A84C;line-height:1.1;}}
      .db-stat-lbl{{font-size:11px;color:#5A4A2A;margin-top:4px;text-transform:uppercase;letter-spacing:.06em;}}
      .db-sec{{background:#0E0C00;border:1px solid rgba(201,168,76,.15);border-radius:12px;padding:16px 18px;margin-bottom:14px;}}
      .db-sec-ttl{{font-size:12px;font-weight:600;color:#C9A84C;text-transform:uppercase;letter-spacing:.10em;margin-bottom:12px;}}
      .db-tag{{display:inline-block;background:#1A1500;border:1px solid rgba(201,168,76,.25);border-radius:20px;padding:3px 10px;font-size:11px;color:#8B7040;margin:2px;}}
    </style>
    <div style="font-family:'DM Sans',sans-serif;padding:4px 0;">
      <div class="db-grid">
        <div class="db-stat"><div class="db-stat-num">{total:,}</div><div class="db-stat-lbl">Total Chunks</div></div>
        <div class="db-stat"><div class="db-stat-num">{queries}</div><div class="db-stat-lbl">Session Queries</div></div>
        <div class="db-stat"><div class="db-stat-num">{conf_r}%</div><div class="db-stat-lbl">Confidence Rate</div></div>
      </div>
      <div class="db-sec">
        <div class="db-sec-ttl">Datasets &amp; Models</div>
        <span class="db-tag">📊 {ds1}</span>
        <span class="db-tag">📊 {ds2}</span>
        <span class="db-tag">🌲 RF: {rf_loaded}</span>
        <span class="db-tag">🌿 DT: {dt_loaded}</span>
        <span class="db-tag">🔑 {num_keys} API key(s)</span>
        <span class="db-tag">🤖 {len(GEMINI_MODELS) + 1} models</span>
      </div>
      <div class="db-sec">
        <div class="db-sec-ttl">Query Topics This Session</div>
        {topic_bars}
      </div>
      <div class="db-sec">
        <div class="db-sec-ttl">Average Retrieval Confidence</div>
        <div style="display:flex;align-items:center;gap:12px;">
          <div style="flex:1;height:10px;background:#1A1A1A;border-radius:5px;overflow:hidden;">
            <div style="height:100%;width:{min(avg_c,100)}%;background:linear-gradient(90deg,#C9A84C,#E8C96A);border-radius:5px;"></div>
          </div>
          <span style="font-size:14px;font-weight:600;color:#C9A84C;">{avg_c}%</span>
        </div>
        <div style="font-size:11px;color:#4A3A20;margin-top:6px;">Based on {len(session_stats["confidence_scores"])} queries</div>
      </div>
      <div class="db-sec">
        <div class="db-sec-ttl">Uploaded This Session ({len(ingested_docs)})</div>
        {docs_html}
      </div>
      <div style="background:#080800;border:1px solid rgba(201,168,76,.10);border-radius:10px;padding:12px 16px;font-size:11px;color:#3A3020;">
        🔒 <strong style="color:#5A4A2A;">Privacy:</strong> PII-anonymized — emails, phones, CNICs redacted.<br>
        ⚡ <strong style="color:#5A4A2A;">Reliability:</strong> Grok routing + Google Gemini Fallback.
      </div>
    </div>"""

# ── Helper: pre-compute comparison table rows (avoids nested f-string issues) ─
def _build_comparison_rows(metrics_list, metric_labels, dt_test, rf_test, DT_COLOR, RF_COLOR):
    rows = []
    for mk, ml in zip(metrics_list, metric_labels):
        dt_v = dt_test.get(mk, 0)
        rf_v = rf_test.get(mk, 0)
        diff = round(rf_v - dt_v, 2)
        diff_str = ("+" + str(diff)) if diff > 0 else str(diff)
        diff_color = "#6fc96f" if diff > 0 else ("#c97060" if diff < 0 else "#5A5A3A")
        dt_fw = "700" if dt_v > rf_v else "400"
        rf_fw = "700" if rf_v > dt_v else "400"
        dt_color = DT_COLOR if dt_v >= rf_v else "#2A3A2A"
        rf_color = RF_COLOR if rf_v >= dt_v else "#3A2A10"
        rows.append(
            f'<tr>'
            f'<td style="font-size:11px;color:#8B7040;padding:6px 8px;border-bottom:1px solid #0E0C00;">{ml}</td>'
            f'<td style="font-size:12px;font-weight:{dt_fw};color:{dt_color};text-align:center;padding:6px 8px;border-bottom:1px solid #0E0C00;">{dt_v}%</td>'
            f'<td style="font-size:12px;font-weight:{rf_fw};color:{rf_color};text-align:center;padding:6px 8px;border-bottom:1px solid #0E0C00;">{rf_v}%</td>'
            f'<td style="font-size:11px;text-align:center;padding:6px 8px;border-bottom:1px solid #0E0C00;color:{diff_color};">{diff_str}%</td>'
            f'</tr>'
        )
    return "".join(rows)


# ── DT vs RF Comparison Chart (pure HTML/CSS — no external libs) ──────────────
def dt_vs_rf_comparison_html(m):
    """
    Renders a grouped bar chart comparing Decision Tree vs Random Forest
    across all three splits (Train / Staging / Test) for 4 metrics.
    Pure HTML + CSS — no JS charting library needed.
    """
    rf_train   = m.get("rf_train",   {})
    rf_staging = m.get("rf_staging", {})
    rf_test    = m.get("rf_test",    {})
    dt_train   = m.get("dt_train",   {})
    dt_staging = m.get("dt_staging", {})
    dt_test    = m.get("dt_test",    {})

    # If no DT data yet, show a helpful message
    if not dt_test:
        return """<div style="background:#0A0800;border:1px solid rgba(201,168,76,.15);border-radius:14px;
                              padding:32px;text-align:center;margin-bottom:14px;">
          <div style="font-size:1.6rem;margin-bottom:10px;">🌿</div>
          <div style="color:#C9A84C;font-weight:600;margin-bottom:6px;">Decision Tree data not found</div>
          <div style="color:#5A4A2A;font-size:.85rem;">
            Re-run <code style="background:#1A1500;padding:2px 8px;border-radius:4px;color:#C9A84C;">python train.py</code>
            to generate DT metrics, then refresh this tab.
          </div></div>"""

    metrics_list = ["accuracy", "precision", "recall", "f1"]
    metric_labels = ["Accuracy", "Precision", "Recall", "F1-Score"]

    DT_COLOR  = "#6fc96f"   # green
    RF_COLOR  = "#C9A84C"   # gold
    DT_DIM    = "#2A4A2A"
    RF_DIM    = "#4A3A10"

    splits = [
        ("Train",   dt_train,   rf_train),
        ("Staging", dt_staging, rf_staging),
        ("Test",    dt_test,    rf_test),
    ]

    # ── grouped bar chart per split ──────────────────────────────────────────
    split_sections = ""
    for split_name, dt_data, rf_data in splits:
        bars_html = ""
        for mk, ml in zip(metrics_list, metric_labels):
            dt_v = dt_data.get(mk, 0)
            rf_v = rf_data.get(mk, 0)
            winner_dt = dt_v > rf_v
            winner_rf = rf_v > dt_v

            bars_html += f"""
            <div style="margin-bottom:16px;">
              <div style="font-size:11px;color:#6B5D3F;text-transform:uppercase;letter-spacing:.08em;margin-bottom:6px;">{ml}</div>
              <!-- DT bar -->
              <div style="display:flex;align-items:center;gap:8px;margin-bottom:4px;">
                <span style="font-size:10px;color:{DT_COLOR};min-width:26px;font-weight:600;">DT</span>
                <div style="flex:1;height:14px;background:#111000;border-radius:4px;overflow:hidden;position:relative;">
                  <div style="height:100%;width:{min(dt_v,100):.1f}%;background:{'linear-gradient(90deg,#4fc94f,#6fe96f)' if winner_dt else DT_DIM};
                       border-radius:4px;transition:width .6s ease;"></div>
                </div>
                <span style="font-size:12px;font-weight:{'700' if winner_dt else '400'};color:{DT_COLOR if winner_dt else '#3A4A3A'};min-width:42px;text-align:right;">{dt_v}%{'★' if winner_dt else ''}</span>
              </div>
              <!-- RF bar -->
              <div style="display:flex;align-items:center;gap:8px;">
                <span style="font-size:10px;color:{RF_COLOR};min-width:26px;font-weight:600;">RF</span>
                <div style="flex:1;height:14px;background:#111000;border-radius:4px;overflow:hidden;position:relative;">
                  <div style="height:100%;width:{min(rf_v,100):.1f}%;background:{'linear-gradient(90deg,#C9A84C,#E8C96A)' if winner_rf else RF_DIM};
                       border-radius:4px;transition:width .6s ease;"></div>
                </div>
                <span style="font-size:12px;font-weight:{'700' if winner_rf else '400'};color:{RF_COLOR if winner_rf else '#4A3A10'};min-width:42px;text-align:right;">{rf_v}%{'★' if winner_rf else ''}</span>
              </div>
            </div>"""

        split_sections += f"""
        <div style="background:#0A0800;border:1px solid rgba(201,168,76,.18);border-radius:12px;
                    padding:18px 20px;flex:1;min-width:220px;">
          <div style="font-size:12px;font-weight:700;color:#C9A84C;text-transform:uppercase;
                      letter-spacing:.12em;margin-bottom:16px;border-bottom:1px solid rgba(201,168,76,.15);
                      padding-bottom:8px;">{split_name} Split</div>
          {bars_html}
        </div>"""

    # ── head-to-head scorecard (test set only) ───────────────────────────────
    dt_wins = sum(1 for mk in metrics_list if dt_test.get(mk,0) > rf_test.get(mk,0))
    rf_wins = sum(1 for mk in metrics_list if rf_test.get(mk,0) > dt_test.get(mk,0))
    ties    = len(metrics_list) - dt_wins - rf_wins
    overall_winner = "Random Forest 🌲" if rf_wins > dt_wins else ("Decision Tree 🌿" if dt_wins > rf_wins else "Tied 🤝")
    overall_color  = RF_COLOR if rf_wins > dt_wins else (DT_COLOR if dt_wins > rf_wins else "#8B8B6A")

    scorecard = f"""
    <div style="background:#0A0800;border:1px solid rgba(201,168,76,.18);border-radius:12px;
                padding:18px 20px;margin-bottom:14px;">
      <div style="font-size:12px;font-weight:700;color:#C9A84C;text-transform:uppercase;
                  letter-spacing:.12em;margin-bottom:16px;border-bottom:1px solid rgba(201,168,76,.15);
                  padding-bottom:8px;">🏆 Head-to-Head: Test Set Scorecard</div>
      <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:16px;">
        <div style="background:#141200;border:1px solid rgba(111,201,111,.25);border-radius:10px;
                    padding:14px;text-align:center;">
          <div style="font-size:26px;font-weight:700;color:{DT_COLOR};">{dt_wins}</div>
          <div style="font-size:10px;color:#3A4A3A;text-transform:uppercase;margin-top:3px;">DT Wins 🌿</div>
        </div>
        <div style="background:#141200;border:1px solid rgba(201,168,76,.15);border-radius:10px;
                    padding:14px;text-align:center;">
          <div style="font-size:26px;font-weight:700;color:#5A5A3A;">{ties}</div>
          <div style="font-size:10px;color:#3A3A2A;text-transform:uppercase;margin-top:3px;">Ties 🤝</div>
        </div>
        <div style="background:#141200;border:1px solid rgba(201,168,76,.25);border-radius:10px;
                    padding:14px;text-align:center;">
          <div style="font-size:26px;font-weight:700;color:{RF_COLOR};">{rf_wins}</div>
          <div style="font-size:10px;color:#5A4A2A;text-transform:uppercase;margin-top:3px;">RF Wins 🌲</div>
        </div>
      </div>
      <div style="background:#141200;border:1px solid rgba(201,168,76,.20);border-radius:8px;
                  padding:12px;text-align:center;">
        <div style="font-size:11px;color:#5A4A2A;text-transform:uppercase;letter-spacing:.08em;margin-bottom:4px;">Overall Winner (Test Set)</div>
        <div style="font-size:18px;font-weight:700;color:{overall_color};">{overall_winner}</div>
      </div>
      <div style="margin-top:14px;">
        <table style="width:100%;border-collapse:collapse;">
          <tr>
            <th style="font-size:10px;color:#4A3A20;text-align:left;padding:5px 8px;border-bottom:1px solid #1A1400;">METRIC</th>
            <th style="font-size:10px;color:{DT_COLOR};text-align:center;padding:5px 8px;border-bottom:1px solid #1A1400;">DT 🌿</th>
            <th style="font-size:10px;color:{RF_COLOR};text-align:center;padding:5px 8px;border-bottom:1px solid #1A1400;">RF 🌲</th>
            <th style="font-size:10px;color:#4A3A20;text-align:center;padding:5px 8px;border-bottom:1px solid #1A1400;">DIFF</th>
          </tr>
          {_build_comparison_rows(metrics_list, metric_labels, dt_test, rf_test, DT_COLOR, RF_COLOR)}
        </table>
        <div style="font-size:10px;color:#3A2A10;margin-top:6px;text-align:right;">DIFF = RF − DT (positive = RF better)</div>
      </div>
    </div>"""

    # ── overfitting indicator ─────────────────────────────────────────────────
    def overfit_badge(train_acc, test_acc, name, color):
        gap = round(train_acc - test_acc, 2)
        if gap > 10:
            level = "⚠️ High Overfit"
            bg = "rgba(200,100,80,.12)"; bc = "rgba(200,100,80,.35)"; tc2 = "#c97060"
        elif gap > 4:
            level = "🟡 Mild Overfit"
            bg = "rgba(201,168,76,.08)"; bc = "rgba(201,168,76,.30)"; tc2 = "#C9A84C"
        else:
            level = "✅ Good Generalization"
            bg = "rgba(100,200,100,.08)"; bc = "rgba(100,200,100,.28)"; tc2 = "#6fc96f"
        return f"""<div style="background:{bg};border:1px solid {bc};border-radius:10px;
                               padding:12px 16px;flex:1;min-width:160px;">
          <div style="font-size:11px;color:{color};font-weight:600;margin-bottom:4px;">{name}</div>
          <div style="font-size:13px;color:{tc2};font-weight:700;">{level}</div>
          <div style="font-size:11px;color:#4A3A20;margin-top:3px;">Train−Test gap: {gap:+.2f}%</div>
        </div>"""

    overfit_section = f"""
    <div style="background:#0A0800;border:1px solid rgba(201,168,76,.18);border-radius:12px;
                padding:18px 20px;margin-bottom:14px;">
      <div style="font-size:12px;font-weight:700;color:#C9A84C;text-transform:uppercase;
                  letter-spacing:.12em;margin-bottom:14px;border-bottom:1px solid rgba(201,168,76,.15);
                  padding-bottom:8px;">📉 Overfitting Analysis</div>
      <div style="display:flex;gap:10px;flex-wrap:wrap;">
        {overfit_badge(dt_train.get('accuracy',0), dt_test.get('accuracy',0), "Decision Tree 🌿", DT_COLOR)}
        {overfit_badge(rf_train.get('accuracy',0), rf_test.get('accuracy',0), "Random Forest 🌲", RF_COLOR)}
      </div>
      <div style="font-size:11px;color:#3A3020;margin-top:10px;line-height:1.6;">
        Large train−test accuracy gaps indicate overfitting. Random Forest mitigates this via ensemble averaging;
        Decision Trees are more prone to memorizing training data unless depth is constrained.
      </div>
    </div>"""

    return f"""
    <div style="font-family:'DM Sans',sans-serif;">
      <div style="background:#0A0800;border:1px solid rgba(201,168,76,.18);border-radius:12px;
                  padding:18px 20px;margin-bottom:14px;">
        <div style="font-size:12px;font-weight:700;color:#C9A84C;text-transform:uppercase;
                    letter-spacing:.12em;margin-bottom:10px;border-bottom:1px solid rgba(201,168,76,.15);
                    padding-bottom:8px;">🌿 Decision Tree vs 🌲 Random Forest — All Splits</div>
        <div style="display:flex;gap:12px;flex-wrap:wrap;">
          {split_sections}
        </div>
        <div style="display:flex;gap:16px;margin-top:12px;font-size:11px;color:#4A3A20;">
          <span><span style="color:{DT_COLOR};font-weight:700;">▌</span> Decision Tree (single tree, depth≤20)</span>
          <span><span style="color:{RF_COLOR};font-weight:700;">▌</span> Random Forest (100 trees, depth≤25)</span>
          <span style="margin-left:auto;">★ = winner for that metric</span>
        </div>
      </div>
      {scorecard}
      {overfit_section}
    </div>"""

# ── Accuracy ──────────────────────────────────────────────────────────────────
def accuracy_html():
    m = load_metrics()
    if not m:
        return """<div style="font-family:'DM Sans',sans-serif;padding:40px;text-align:center;">
          <div style="font-size:2rem;margin-bottom:16px;color:#C9A84C;">⚙️</div>
          <div style="font-size:1.1rem;color:#C9A84C;font-weight:600;margin-bottom:8px;">No Training Data Yet</div>
          <div style="font-size:.88rem;color:#5A4A2A;line-height:1.7;">
            Run <code style="background:#1A1500;padding:2px 8px;border-radius:4px;color:#C9A84C;">python train.py</code>
            to generate metrics.
          </div></div>"""

    chroma_h5=round(m.get("chroma_hit_at_k",0)*100,1)
    tfidf_h5 =round(m.get("tfidf_hit_at_k", 0)*100,1)
    tfidf_p5 =round(m.get("tfidf_precision",0)*100,1)
    tfidf_r10=round(m.get("tfidf_recall",   0)*100,1)
    improv   =m.get("improvement_pct",0)
    eval_n   =m.get("eval_set_size",0)
    f1_rag   =m.get("rag_f1",0)
    tp_r=m.get("rag_tp",0); fp_r=m.get("rag_fp",0)
    fn_r=m.get("rag_fn",0); tn_r=m.get("rag_tn",0)
    topic_sc =m.get("topic_scores",{})
    ds1=m.get("dataset1_source","neduet_faq_50k.csv")
    ds2=m.get("dataset2_source","neduet_courses.csv")
    faq_rows=m.get("faq_rows",0); cat_rows=m.get("catalog_rows",0)
    chunks=m.get("total_chunks",0); ts=m.get("timestamp","—")[:16].replace("T"," ")
    rf_train  =m.get("rf_train",  {}); rf_staging=m.get("rf_staging",{})
    rf_test   =m.get("rf_test",   {}); rf_classes=m.get("rf_classes",[])

    def bar(val, color="#C9A84C", height=11):
        return (f'<div style="flex:1;height:{height}px;background:#1A1A1A;border-radius:5px;overflow:hidden;">'
                f'<div style="height:100%;width:{min(float(val),100):.1f}%;background:{color};border-radius:5px;"></div></div>')

    def rf_card(label, data, bcolor, accent):
        if not data: return ""
        acc=data.get("accuracy",0); prec=data.get("precision",0)
        rec=data.get("recall",0);   f1=data.get("f1",0)
        n=data.get("n_samples",0);  cm=data.get("confusion_matrix",[])
        cls=data.get("classes",rf_classes)
        cm_html=""
        if cm and cls:
            hdr="".join(f'<th style="padding:3px 6px;font-size:9px;color:#8B7040;">{c[:5]}</th>'for c in cls)
            rws=""
            for i,row in enumerate(cm):
                cells="".join(f'<td style="padding:3px 6px;text-align:center;font-size:11px;color:{"#C9A84C"if i==j else"#4A3A20"};font-weight:{"600"if i==j else"400"};">{v}</td>'for j,v in enumerate(row))
                rws+=f'<tr><td style="padding:3px 6px;font-size:9px;color:#8B7040;">{cls[i][:7]}</td>{cells}</tr>'
            cm_html=f"""<div style="margin-top:12px;overflow-x:auto;">
              <div style="font-size:10px;color:#4A3A20;text-transform:uppercase;margin-bottom:5px;">Confusion Matrix</div>
              <table style="border-collapse:collapse;width:100%;min-width:300px;"><tr><th></th>{hdr}</tr>{rws}</table></div>"""
        return f"""
        <div style="background:#0A0800;border:1px solid {bcolor};border-radius:12px;padding:16px 18px;margin-bottom:12px;">
          <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px;">
            <div style="font-size:13px;font-weight:600;color:{accent};">{label}</div>
            <div style="font-size:11px;color:#5A4A2A;">{n:,} samples</div>
          </div>
          <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-bottom:14px;">
            {" ".join(f'<div style="background:#141200;border-radius:8px;padding:10px 6px;text-align:center;"><div style="font-size:18px;font-weight:700;color:{accent};">{v}%</div><div style="font-size:9px;color:#5A4A2A;margin-top:2px;text-transform:uppercase;">{k}</div></div>'for k,v in[("Accuracy",acc),("Precision",prec),("Recall",rec),("F1",f1)])}
          </div>
          <div style="display:flex;flex-direction:column;gap:7px;">
            {" ".join(f'<div style="display:flex;align-items:center;gap:8px;"><span style="font-size:11px;color:#6B5D3F;min-width:70px;">{k}</span>{bar(v,accent)}<span style="font-size:11px;font-weight:600;color:{accent};min-width:36px;">{v}%</span></div>'for k,v in[("Accuracy",acc),("Precision",prec),("Recall",rec),("F1-score",f1)])}
          </div>{cm_html}</div>"""

    TCOLS={"Finance":"#C9A84C","Admissions":"#E8C96A","Academics":"#B89040","Facilities":"#D4B060","Exams":"#A07830","General":"#786030"}
    topic_rows="".join(f"""
      <div style="margin-bottom:12px;">
        <div style="display:flex;justify-content:space-between;font-size:12px;margin-bottom:4px;">
          <span style="color:{TCOLS.get(t,'#C9A84C')};font-weight:500;">{t}</span>
          <span style="color:#8B7040;">{sc}%</span>
        </div>
        <div style="display:flex;align-items:center;gap:10px;">{bar(sc,TCOLS.get(t,'#C9A84C'))}</div>
      </div>""" for t,sc in topic_sc.items()
    ) or '<p style="color:#4A3A20;font-size:13px;">Topic breakdown not available.</p>'

    return f"""
    <style>
      .ac-g4{{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:20px;}}
      .ac-st{{background:#141200;border:1px solid rgba(201,168,76,.20);border-radius:12px;padding:16px 12px;text-align:center;}}
      .ac-num{{font-size:24px;font-weight:700;color:#C9A84C;line-height:1.1;}}
      .ac-lbl{{font-size:10px;color:#5A4A2A;margin-top:4px;text-transform:uppercase;letter-spacing:.07em;}}
      .ac-sec{{background:#0E0C00;border:1px solid rgba(201,168,76,.15);border-radius:14px;padding:18px 20px;margin-bottom:14px;}}
      .ac-ttl{{font-size:12px;font-weight:600;color:#C9A84C;text-transform:uppercase;letter-spacing:.10em;margin-bottom:14px;border-bottom:1px solid rgba(201,168,76,.12);padding-bottom:8px;}}
      .ac-row{{display:flex;align-items:center;gap:12px;margin-bottom:12px;}}
      .badge-up{{display:inline-block;background:rgba(100,200,100,.15);border:1px solid rgba(100,200,100,.3);color:#6fc96f;border-radius:20px;padding:4px 14px;font-size:12px;font-weight:600;}}
      .ds-tag{{background:#1A1500;border:1px solid rgba(201,168,76,.25);border-radius:20px;padding:4px 12px;font-size:11px;color:#8B7040;display:inline-block;margin:2px;}}
      .conf-g{{display:grid;grid-template-columns:1fr 1fr;gap:8px;}}
      .conf-c{{border-radius:8px;padding:12px;text-align:center;}}
    </style>
    <div style="font-family:'DM Sans',sans-serif;padding:4px 0;">
      <div class="ac-g4">
        <div class="ac-st"><div class="ac-num">{chroma_h5}%</div><div class="ac-lbl">RAG Hit@5</div></div>
        <div class="ac-st"><div class="ac-num">{rf_test.get("accuracy",0)}%</div><div class="ac-lbl">RF Test Acc.</div></div>
        <div class="ac-st"><div class="ac-num">{f1_rag}%</div><div class="ac-lbl">RAG F1</div></div>
        <div class="ac-st"><div class="ac-num">+{improv}%</div><div class="ac-lbl">RAG Improvement</div></div>
      </div>
      <div class="ac-sec">
        <div class="ac-ttl">📊 Training Data Overview</div>
        <div style="margin-bottom:12px;">
          <span class="ds-tag">Dataset 1: {ds1}</span>
          <span class="ds-tag">Dataset 2: {ds2}</span>
          <span class="ds-tag">Eval: {eval_n} pairs</span>
          <span class="ds-tag">Trained: {ts}</span>
        </div>
        <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px;">
          {" ".join(f'<div style="background:#141200;border:1px solid rgba(201,168,76,.15);border-radius:8px;padding:10px;text-align:center;"><div style="font-size:18px;font-weight:600;color:#C9A84C;">{v:,}</div><div style="font-size:9px;color:#5A4A2A;margin-top:2px;text-transform:uppercase;">{k}</div></div>'for k,v in[("FAQ Rows",faq_rows),("Catalog Rows",cat_rows),("DB Chunks",chunks)])}
        </div>
      </div>

      <!-- ══ NEW: DT vs RF COMPARISON ══ -->
      <div class="ac-sec">
        <div class="ac-ttl">🌿🌲 Decision Tree vs Random Forest — Comparison</div>
        {dt_vs_rf_comparison_html(m)}
      </div>

      <div class="ac-sec">
        <div class="ac-ttl">🌲 Random Forest — Train / Staging / Test</div>
        <div style="font-size:11px;color:#4A3A20;margin-bottom:14px;line-height:1.6;">
          TF-IDF features, max_depth=25, min_samples_leaf=4. Split: <strong style="color:#6B5D3F;">70% train · 15% staging · 15% test</strong>.
        </div>
        {rf_card("🟢 Training Set", rf_train,  "rgba(100,200,100,.3)","#6fc96f")}
        {rf_card("🟡 Staging Set",  rf_staging,"rgba(201,168,76,.3)", "#C9A84C")}
        {rf_card("🔴 Test Set",      rf_test,   "rgba(200,100,80,.3)", "#c97060")}
      </div>
      <div class="ac-sec">
        <div class="ac-ttl">🤖 RAG — TF-IDF vs Semantic Embeddings</div>
        <div class="ac-row">
          <span style="font-size:12px;color:#6B5B35;min-width:220px;">Baseline — TF-IDF</span>
          {bar(tfidf_h5,"#4A3A18")}
          <span style="font-size:13px;font-weight:600;color:#8B7040;min-width:44px;">{tfidf_h5}%</span>
        </div>
        <div class="ac-row">
          <span style="font-size:12px;color:#C9A84C;min-width:220px;">Improved — Semantic Embeddings</span>
          {bar(chroma_h5,"linear-gradient(90deg,#C9A84C,#E8C96A)")}
          <span style="font-size:13px;font-weight:600;color:#C9A84C;min-width:44px;">{chroma_h5}%</span>
        </div>
        <div style="margin-top:12px;"><span class="badge-up">▲ +{improv}% improvement</span></div>
      </div>
      <div class="ac-sec">
        <div class="ac-ttl">📐 TF-IDF Baseline Metrics</div>
        {" ".join(f'<div class="ac-row"><span style="font-size:12px;color:#8B7040;min-width:120px;">{k}</span>{bar(v,"#5A4A20")}<span style="font-size:12px;font-weight:600;color:#8B7040;min-width:44px;">{v}%</span></div>'for k,v in[("Hit@5",tfidf_h5),("Precision@5",tfidf_p5),("Recall@10",tfidf_r10)])}
      </div>
      <div class="ac-sec">
        <div class="ac-ttl">🔢 RAG Confusion Matrix (n={eval_n})</div>
        <div class="conf-g">
          {" ".join(f'<div class="conf-c" style="background:{bg};border:1px solid {bc};"><div style="font-size:20px;font-weight:700;color:{tc};">{v}</div><div style="font-size:9px;color:{tc};opacity:.75;margin-top:2px;text-transform:uppercase;">{lbl}</div></div>'for lbl,v,bg,bc,tc in[("True Positive",tp_r,"rgba(100,200,100,.08)","rgba(100,200,100,.25)","#6fc96f"),("False Positive",fp_r,"rgba(201,168,76,.06)","rgba(201,168,76,.20)","#8B7040"),("False Negative",fn_r,"rgba(200,100,80,.06)","rgba(200,100,80,.20)","#c97060"),("True Negative",tn_r,"rgba(100,150,200,.06)","rgba(100,150,200,.20)","#6090c9")])}
        </div>
      </div>
      <div class="ac-sec">
        <div class="ac-ttl">🏷️ Per-Topic RAG Accuracy</div>
        {topic_rows}
      </div>
    </div>"""

# ── CSS ────────────────────────────────────────────────────────────────────────
CUSTOM_CSS = """
@import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@400;600;700&family=DM+Sans:wght@300;400;500;600&display=swap');
*,*::before,*::after{box-sizing:border-box;}
:root{--gold:#C9A84C;--gold-light:#E8C96A;--gold-dim:#8B6914;--gold-glow:rgba(201,168,76,.14);--gold-border:rgba(201,168,76,.28);--black:#080808;--panel:#101008;--card:#181600;--text:#EDE0C0;--muted:#6B5D3F;}
body,.gradio-container{font-family:'DM Sans',sans-serif !important;background:var(--black) !important;color:var(--text) !important;}
.gradio-container .wrap,.gradio-container .gap,.gradio-container section,.gradio-container .contain,.gradio-container .block{background:transparent !important;border-color:transparent !important;}
footer{display:none !important;}
::-webkit-scrollbar{width:5px;}::-webkit-scrollbar-track{background:#0A0A00;}::-webkit-scrollbar-thumb{background:var(--gold-dim);border-radius:3px;}
.cb-header{background:linear-gradient(135deg,#0E0C00,#181200);border-radius:18px;padding:18px 26px;margin-bottom:18px;display:flex;align-items:center;gap:18px;border:1px solid var(--gold-border);box-shadow:0 0 40px rgba(201,168,76,.08),0 8px 32px rgba(0,0,0,.7);position:relative;overflow:hidden;}
.cb-header::before{content:'';position:absolute;top:0;left:0;right:0;height:1px;background:linear-gradient(90deg,transparent,var(--gold),transparent);opacity:.6;}
.cb-logo-wrap{width:54px;height:54px;border-radius:14px;background:linear-gradient(145deg,#1c1500,#2e2000);border:1.5px solid var(--gold-border);display:flex;align-items:center;justify-content:center;flex-shrink:0;box-shadow:0 0 16px rgba(201,168,76,.18);}
.cb-brand{display:flex;flex-direction:column;gap:2px;}
.cb-name{font-family:'Cinzel',serif !important;font-size:1.5rem !important;font-weight:700 !important;background:linear-gradient(135deg,#F0D878,#C9A84C,#8B6010) !important;-webkit-background-clip:text !important;-webkit-text-fill-color:transparent !important;background-clip:text !important;letter-spacing:.07em !important;line-height:1.1 !important;}
.cb-sub{font-size:.78rem !important;color:var(--muted) !important;letter-spacing:.10em !important;text-transform:uppercase !important;}
.tabs,.tab-nav{background:transparent !important;border:none !important;}
.tab-nav{border-bottom:1px solid var(--gold-border) !important;margin-bottom:18px !important;gap:0 !important;padding:0 !important;}
.tab-nav button{border:none !important;font-weight:500 !important;font-size:.87rem !important;color:var(--muted) !important;padding:10px 20px !important;background:transparent !important;border-bottom:2px solid transparent !important;margin-bottom:-1px !important;transition:all .2s ease !important;letter-spacing:.04em !important;}
.tab-nav button:hover{color:var(--gold-light) !important;}
.tab-nav button.selected{color:var(--gold) !important;border-bottom:2px solid var(--gold) !important;background:var(--gold-glow) !important;}
.chatbot,div[data-testid="chatbot"],.chatbot>div,.chatbot .wrap{background:var(--panel) !important;border:1px solid var(--gold-border) !important;border-radius:20px !important;box-shadow:0 8px 40px rgba(0,0,0,.6) !important;}
.avatar-container,.avatar-container img,img.avatar,[class*="avatar"],.message-row>div:first-child img{display:none !important;width:0 !important;height:0 !important;visibility:hidden !important;position:absolute !important;}
.label-wrap,.label-wrap *,[data-testid="chatbot"]>label,.block.chatbot>label,.block>.label-wrap{display:none !important;}
.message.user .message-wrap,[data-testid="user"] .message-wrap{background:linear-gradient(135deg,#1c1500,#2a1e00) !important;color:var(--gold-light) !important;border:1px solid var(--gold-border) !important;border-radius:18px 18px 4px 18px !important;padding:12px 18px !important;font-size:.92rem !important;max-width:76% !important;margin-left:auto !important;}
.message.bot .message-wrap,[data-testid="bot"] .message-wrap{background:var(--card) !important;color:var(--text) !important;border:1px solid #252000 !important;border-left:3px solid var(--gold) !important;border-radius:4px 18px 18px 18px !important;padding:14px 20px !important;font-size:.92rem !important;line-height:1.68 !important;max-width:88% !important;}
textarea,input[type="text"]{background:var(--card) !important;border:1px solid var(--gold-border) !important;border-radius:50px !important;padding:13px 22px !important;color:var(--text) !important;font-size:.93rem !important;transition:all .2s ease !important;caret-color:var(--gold) !important;}
textarea:focus,input[type="text"]:focus{border-color:var(--gold) !important;box-shadow:0 0 0 3px var(--gold-glow) !important;outline:none !important;}
textarea::placeholder,input::placeholder{color:var(--muted) !important;}
button[aria-label="Send"],button.primary,.gr-button-primary{background:linear-gradient(135deg,var(--gold-light),var(--gold),#8B6010) !important;color:#0A0800 !important;border-radius:50px !important;font-weight:700 !important;border:none !important;letter-spacing:.05em !important;transition:all .2s ease !important;box-shadow:0 2px 16px rgba(201,168,76,.28) !important;}
button[aria-label="Send"]:hover,button.primary:hover{box-shadow:0 4px 24px rgba(201,168,76,.48) !important;transform:translateY(-1px) !important;filter:brightness(1.1) !important;}
button.secondary,.gr-button-secondary{background:transparent !important;border:1px solid var(--gold-border) !important;color:var(--gold) !important;border-radius:50px !important;transition:all .2s ease !important;}
button.secondary:hover{background:var(--gold-glow) !important;border-color:var(--gold) !important;}
.examples button,.examples-holder button{background:var(--card) !important;border:1px solid var(--gold-border) !important;color:var(--muted) !important;border-radius:100px !important;font-size:.81rem !important;padding:8px 16px !important;transition:all .22s ease !important;}
.examples button:hover{border-color:var(--gold) !important;color:var(--gold) !important;background:var(--gold-glow) !important;}
.upload-container,[data-testid="file-upload"]{background:var(--card) !important;border:2px dashed var(--gold-border) !important;border-radius:14px !important;color:var(--muted) !important;}
.prose strong,.markdown strong{color:var(--gold-light) !important;}
.prose h3,.markdown h3{font-family:'Cinzel',serif !important;color:var(--gold) !important;border-bottom:1px solid var(--gold-border) !important;padding-bottom:6px !important;}
.prose code,.markdown code{background:#1A1500 !important;color:var(--gold) !important;padding:2px 6px !important;border-radius:4px !important;}
.message-buttons button{color:var(--muted) !important;background:transparent !important;border:none !important;}
.message-buttons button:hover{color:var(--gold) !important;}
hr{border-color:var(--gold-border) !important;}
@keyframes shimmer{0%,100%{opacity:.4}50%{opacity:1}}
.cb-header:hover::before{animation:shimmer 2s ease infinite;}
"""

HEADER_HTML = """
<div class="cb-header">
  <div class="cb-logo-wrap">
    <svg width="28" height="28" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
      <polygon points="16,2 20,12 31,12 22,19 25.5,29.5 16,23 6.5,29.5 10,19 1,12 12,12" fill="url(#g1)"/>
      <defs><linearGradient id="g1" x1="1" y1="2" x2="31" y2="30" gradientUnits="userSpaceOnUse">
        <stop offset="0%" stop-color="#F0D878"/>
        <stop offset="55%" stop-color="#C9A84C"/>
        <stop offset="100%" stop-color="#7A5510"/>
      </linearGradient></defs>
    </svg>
  </div>
  <div class="cb-brand">
    <div class="cb-name">CampusBrain</div>
    <div class="cb-sub">Intelligent Knowledge Base &nbsp;·&nbsp; NED University</div>
  </div>
</div>"""

JS_DARK = """function refresh(){const u=new URL(window.location);if(u.searchParams.get('__theme')!=='dark'){u.searchParams.set('__theme','dark');window.location.replace(u.href);}}"""

PLACEHOLDER = """
<div style="text-align:center;padding:65px 20px;background:transparent;">
  <div style="font-size:2.2rem;margin-bottom:12px;filter:drop-shadow(0 0 12px rgba(201,168,76,.45));">✦</div>
  <div style="font-size:1.25rem;font-weight:600;color:#C9A84C;letter-spacing:.05em;font-family:'Cinzel',serif;">How can I assist you?</div>
  <div style="font-size:.85rem;margin-top:9px;color:#4A3A20;max-width:340px;margin-left:auto;margin-right:auto;line-height:1.65;">
    Ask anything about NED University — admissions, policies, scholarships, courses, and facilities.
  </div>
</div>"""

# ── Build UI ──────────────────────────────────────────────────────────────────
with gr.Blocks(title="CampusBrain — NED University") as demo:

    gr.HTML(HEADER_HTML)

    with gr.Tabs():

        with gr.TabItem("✦  Assistant"):
            gr.ChatInterface(
                fn=chat,
                chatbot=gr.Chatbot(
                    height=510,
                    render_markdown=True,
                    avatar_images=(None, None),
                    placeholder=PLACEHOLDER,
                    label="",
                    show_label=False,
                ),
                textbox=gr.Textbox(
                    placeholder="Ask a question about NED University…",
                    container=False,
                    scale=8,
                    elem_classes=["cb-input"],
                ),
                examples=[
                    "What is the maximum credit hour limit for registration?",
                    "How does the Qarz-e-Hasana loan work?",
                    "Where is the Engr. Abul Kalam Library?",
                    "What happens if my CGPA falls below 2.50?",
                    "What courses are offered in Computer Science?",
                    "How do I apply for admission at NED?",
                ],
                cache_examples=False,
                submit_btn="Send ➤",
            )

        with gr.TabItem("◈  Knowledge Base"):
            gr.Markdown(
                "### Upload Documents\n"
                "Extend CampusBrain's knowledge with PDFs or TXT files. "
                "All content is **PII-anonymized** automatically."
            )
            file_input = gr.File(
                label="Drop files here (.pdf or .txt)",
                file_types=[".pdf", ".txt"],
                file_count="multiple",
            )
            with gr.Row():
                upload_btn = gr.Button("Ingest Documents", variant="primary",  scale=2)
                clear_btn  = gr.Button("Clear",            variant="secondary", scale=1)
            upload_status = gr.Textbox(
                label="", show_label=False, interactive=False,
                placeholder="Upload results appear here…",
            )
            upload_btn.click(handle_upload, inputs=file_input, outputs=upload_status)
            clear_btn.click(lambda: "", outputs=upload_status)

        with gr.TabItem("📊  Accuracy"):
            acc = gr.HTML(accuracy_html())
            gr.Button("↻  Refresh", variant="secondary").click(accuracy_html, outputs=acc)

        with gr.TabItem("◉  Dashboard"):
            dash = gr.HTML(dashboard_html())
            gr.Button("↻  Refresh", variant="secondary").click(dashboard_html, outputs=dash)

if __name__ == "__main__":
    demo.launch(
        debug=True,
        theme=gr.themes.Base(),
        css=CUSTOM_CSS,
        js=JS_DARK,
    )